---
  - name: check if src repo exists
    stat: 
      path: /jenkins-server/iTrust2-v4
    register: src_repo
  
  - name: Clone from GitHub
    git:
      repo: git@github.ncsu.edu:sbhoyar/iTrust2-v4.git
      dest: /jenkins-server/iTrust2-v4
      accept_hostkey: yes
      key_file: /root/.ssh/id_rsa_github
    when: src_repo.stat.exists == False
    become: true

  - name: Configure git post-receive push options
    command: chdir=/jenkins-server/iTrust2-v4 git config --local push.pushOption {{jenkins_user}}
    when: src_repo.stat.exists == False
  
  - name: Configure git post-receive push options
    command: chdir=/jenkins-server/iTrust2-v4 git config --local push.pushOption {{jenkins_password}} {{jenkins_password}}
    when: src_repo.stat.exists == False

  - name: Create bare repository for hook
    command: git init --bare /jenkins-server/iTrust2-v4/build/jenkins.git/
    become: true
    when: src_repo.stat.exists == False

  - name: Configure bare repo to receive push options
    git_config:
      name: receive.advertisePushOptions
      value: true
      scope: local
      repo: /jenkins-server/iTrust2-v4/build/jenkins.git/

