---
  - name: Clone checkbox private repository
    git:
      repo: "https://{{ github_username }}:{{ github_password }}@github.ncsu.edu/asaxena5/checkbox.io-private.git"
      dest: /home/checkbox/
      version: master
    become: yes
  
  - name: Creates deploy directory
    become: yes
    file:
      path: /home/checkbox/deploy
      state: directory
  
  - name: Creates production-www directory
    become: yes
    file:
      path: /home/checkbox/deploy/production-www
      state: directory
  
  - name: Creates production.git directory
    become: yes
    file:
      path: '{{ git_repository_path }}'
      state: directory
      mode: ug+rw
  
  - name: git init
    command: git init --bare
    args:
      chdir: '{{ git_repository_path }}'
    become: yes
  
  - name: Copy post-receive script
    action: template src=roles/jenkins_build_job/templates/hooks/postreceive.j2 dest={{ git_repository_path }}/hooks/post-receive mode=0755
    become: yes

  - name: Get list of jobs
    uri: url="http://localhost:8080/api/json?tree=jobs[name]" return_content=yes
    register: jobs

  - name: Check if job exists
    set_fact:
      seed_exists: "{{ seed_name in jobs.json.jobs|map(attribute='name')|list }}"

  - name: Create job
    uri:
      url: "http://localhost:8080/createItem?name={{ seed_name }}"
      method: POST
      HEADER_Content-Type: application/xml
      body: "{{ lookup('template', 'roles/jenkins_build_job/templates/pipelineJob.xml') }}"
    register: jenkins_seed_updated
    when: not seed_exists

  - name: Build job
    uri:
      url: "http://localhost:8080/job/{{ seed_name }}/build"
      method: POST
      status_code: 201
    when: jenkins_seed_updated is success