---
  - name: Get list of jobs
    uri: url="http://localhost:8081/api/json?tree=jobs[name]" return_content=yes
    register: jobs

  - name: Check if job exists
    set_fact:
      seed_exists: "{{ seed_name in jobs.json.jobs|map(attribute='name')|list }}"

  - name: Create job
    uri:
      url: "http://localhost:8081/createItem?name={{ seed_name }}"
      method: POST
      HEADER_Content-Type: application/xml
      body: "{{ lookup('template', 'roles/jenkins_build_job/templates/pipelineJob.xml') }}"
    register: jenkins_seed_updated
    when: not seed_exists

  - name: Build job
    uri:
      url: "http://localhost:8081/job/{{ seed_name }}/build"
      method: POST
      status_code: 201
    when: jenkins_seed_updated is success