---
  - name: Add git repo for minimum 2.10 version.
    apt_repository:
      repo: ppa:git-core/ppa
    become: true

  - name: Add Oracle Java Repository
    apt_repository:
      repo: ppa:webupd8team/java
    become: true

  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: dist
      update_cache: yes

  - name: Add jenkins repository key
    apt_key:
     url: https://pkg.jenkins.io/debian/jenkins.io.key
     state: present
    become: true

  - name: Add jenkins repo list file into sources.list.d
    apt_repository:
     repo: deb http://pkg.jenkins.io/debian-stable binary/
     state: present
    become: true

  - name: agree to license
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    become: true

  - name: Install jenkins and python wrapper and git
    apt:
     pkg:
       - git
       - oracle-java8-installer
       - python-dev
       - python-jenkins
       - jenkins
       - python-lxml
       - maven
     state: present
    become: true
  
  - name: Start the server
    service:
      name: jenkins
      state: started
  
  - name: read the passwd file
    command: cat /etc/default/jenkins
    register: jenkins_default
    
  - name : Wait for the the jenkins service to start on 8081
    wait_for:
      port: 8081
      delay: 45
    when: jenkins_default.stdout.find('HTTP_PORT=8081') != -1
  
  - name : Wait for the the jenkins service to start on port 8080
    wait_for:
      port: 8080
      delay: 45
    when: jenkins_default.stdout.find('HTTP_PORT=8081') == -1
