---
  - import_tasks: install.yml

  - name: Read Admin password
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: admin_password
    become: true

  - name: Unlock and add admin user
    jenkins_script:
      script: |
        import jenkins.model.*
        import hudson.security.*
        def instance = Jenkins.getInstance()
        def hudsonRealm = new HudsonPrivateSecurityRealm(false)
        def users = hudsonRealm.getAllUsers()
        users_s = users.collect { it.toString() }
        if ("jenkins" in users_s) {
            println "Admin user already exists"
        } else {
          hudsonRealm.createAccount('jenkins', '${jenkins_password}')
          instance.setSecurityRealm(hudsonRealm)
          def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
          strategy.setAllowAnonymousRead(false)
          instance.setAuthorizationStrategy(strategy)
          instance.save()
        }
      args:
        jenkins_password: "{{ jenkins_password }}"
      user: admin
      password: "{{ admin_password.stdout }}"

  - name: Complete the setup wizard
    jenkins_script:
     script: |
      import static jenkins.model.Jenkins.instance as jenkins
      import jenkins.install.InstallState
      if (!jenkins.installState.isSetupComplete()) {
        InstallState.INITIAL_SETUP_COMPLETED.initializeState()
      }
     user: admin
     password: "{{ admin_password.stdout }}"

  - name: Install Jenkins plugins
    jenkins_plugin:
      jenkins_home: "/var/lib/jenkins"
      name: "{{ item }}"
      url_username: "{{jenkins_user}}"
      url_password: "{{ jenkins_password }}"
    with_items:
      - maven-plugin
      - git
      - github
      - nodeJS
      - pipeline-npm-integration
      - workflow-job
      - workflow-scm-step
      - build-pipeline-plugin
      - workflow-aggregator
    register: plugin_result
    until: plugin_result is success
    retries: 3
    delay: 2
  
  - name: Configure jenkins to use port 8081
    lineinfile:
      path: /etc/default/jenkins
      regexp: '^HTTP_PORT='
      line: 'HTTP_PORT=8081'
    become: true
  
  - name: Allow port 8081
    become: true
    ufw:
      rule: allow
      port: '8081'

  - name : Restart Jenkins service
    service: 
      name: jenkins
      state: restarted  
    become: yes

  - name : Wait for the the jenkins service to restart
    wait_for:
      port: 8081
      delay: 45
